### ISSUE TITLE
BUG - Crear Usuario, en la casilla de celular sale el correo.

### ISSUE THREAD

**Issue by MilagrosPalomino** [gustavo-alarcon/ms-crc-lajoya#68]
Cambiar titulo de casilla correo colocar celular.

**Comment by gustavo-alarcon** [comment]
He cambiado el tipo de input a ````number```` , pero no estoy seguro si el error que mencionas es porque Google autocompleta el campo con el correo, o porque motivo.

Si puedes, adjunta una foto con el problema, para guiarme mejor.

**Comment by gustavo-alarcon** [comment]
Por favor, revisa si el cambio corrige el error.
